"mostly Pydantic models for data validation and serialization"
from  datetime import datetime
from pydantic import BaseModel #does data validation and settings management using python type annotations

#splitting models helps if we only want certain fields to be required for creation vs update
class PostBase(BaseModel): 
    title: str #does not check for string, will try to convert if possible
    content: str
    published: bool = True

class PostCreate(PostBase): 
    pass

#responses no longer include fields like 'created_at' that are auto generated by the db
class PostResponse(PostBase): #extending PostBase to avoid repetition
    id: int
    created_at: datetime
    class Config:
        orm_mode = True #tells pydantic model to read data even if it is not a dict, like an ORM model or DB model

class UserCreate(BaseModel):
    email: str
    password: str

class UserResponse(BaseModel):
    email: str
    class Config:
        orm_mode = True

class UserLogin(BaseModel):
    email: str
    password: str
    class Config:
        orm_mode = True